# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.16.0
      - name: npm install
        run: npm install
      - name: elm-pages build
        run: npm run build
      
      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v3.1.0
        with:
          # Directory to deploy
          folder: dist
          # Name of AWS Bucket
          bucket: ${{ secrets.S3_BUCKET }}
          # The destination bucket region
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          invalidation: /
          delete-removed: true
          private: true
